/**
 * ════════════════════════════════════════════════════════════════
 * Contratos — mock data
 * ════════════════════════════════════════════════════════════════
 *
 * Usado em dois lugares:
 *   1. Playground (`/_ds/playground/juridico`) — sempre renderiza
 *      com este dataset.
 *   2. `useContracts` em prod — fallback quando a tabela
 *      `public.contracts` está vazia, ou quando a query falha
 *      (tabela ausente / RLS negando). Some assim que o webhook do
 *      ZapSign começar a popular dados reais.
 *
 * 8 contratos sintéticos cobrindo os estados típicos: aguardando
 * vinculação, awaiting client/internal, signed, expired, recurring
 * active / expiring crítico / expired.
 */

import type { Contract } from './types';

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

export const MOCK_CONTRACTS: Contract[] = [
  // 1 · Project · awaiting_client (em andamento, vinculado)
  {
    id: 'c1',
    zapsign_doc_token: 'tok_c1',
    title: 'Contrato de Produção Audiovisual — Campanha Verão 2026',
    status: 'awaiting_client',
    party_type: 'client',
    contract_class: 'project',
    recurrence: null,
    signers: [
      {
        zapsign_token: 's1a',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 1,
        signed_at: daysAgo(2),
        refused_at: null,
      },
      {
        zapsign_token: 's1b',
        name: 'Marina Ferraz',
        email: 'marina@brandx.com.br',
        role: 'external',
        position: 2,
        signed_at: null,
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(4),
    sent_at: daysAgo(3),
    completed_at: null,
    expires_at: null,
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c1',
    signed_pdf_url: null,
    linked_client_id: 'cli-brandx',
    linked_client_name: 'BrandX Cosmetics',
    linked_project_id: 'prj-verao26',
    linked_project_name: 'Campanha Verão 2026',
    linked_supplier_id: null,
    linked_supplier_name: null,
    value_brl: 84000,
    linked_at: daysAgo(3),
    notes: null,
    imported_at: daysAgo(4),
  },

  // 2 · Project · draft, não vinculado (vai pro bucket "Aguardando vinculação")
  {
    id: 'c2',
    zapsign_doc_token: 'tok_c2',
    title: 'NDA — Pré-produção Projeto Confidencial',
    status: 'draft',
    party_type: 'nda',
    contract_class: 'project',
    recurrence: null,
    signers: [
      {
        zapsign_token: 's2a',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 1,
        signed_at: null,
        refused_at: null,
      },
      {
        zapsign_token: 's2b',
        name: 'João Silva',
        email: 'joao@cliente.com',
        role: 'external',
        position: 2,
        signed_at: null,
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(1),
    sent_at: null,
    completed_at: null,
    expires_at: null,
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c2',
    signed_pdf_url: null,
    linked_client_id: null,
    linked_client_name: null,
    linked_project_id: null,
    linked_project_name: null,
    linked_supplier_id: null,
    linked_supplier_name: null,
    value_brl: null,
    linked_at: null,
    notes: null,
    imported_at: daysAgo(1),
  },

  // 3 · Project · awaiting_internal (alguém da casa precisa assinar)
  {
    id: 'c3',
    zapsign_doc_token: 'tok_c3',
    title: 'Cessão de Imagem — Talent Mariana Costa',
    status: 'awaiting_internal',
    party_type: 'talent',
    contract_class: 'project',
    recurrence: null,
    signers: [
      {
        zapsign_token: 's3a',
        name: 'Mariana Costa',
        email: 'mariana@email.com',
        role: 'external',
        position: 1,
        signed_at: daysAgo(1),
        refused_at: null,
      },
      {
        zapsign_token: 's3b',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 2,
        signed_at: null,
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(2),
    sent_at: daysAgo(2),
    completed_at: null,
    expires_at: null,
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c3',
    signed_pdf_url: null,
    linked_client_id: 'cli-brandx',
    linked_client_name: 'BrandX Cosmetics',
    linked_project_id: 'prj-verao26',
    linked_project_name: 'Campanha Verão 2026',
    linked_supplier_id: null,
    linked_supplier_name: null,
    value_brl: 5000,
    linked_at: daysAgo(2),
    notes: null,
    imported_at: daysAgo(2),
  },

  // 4 · Project · signed (assinado recente)
  {
    id: 'c4',
    zapsign_doc_token: 'tok_c4',
    title: 'Contrato de Edição — Freelancer Carla Lima',
    status: 'signed',
    party_type: 'freelancer',
    contract_class: 'project',
    recurrence: null,
    signers: [
      {
        zapsign_token: 's4a',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 1,
        signed_at: daysAgo(12),
        refused_at: null,
      },
      {
        zapsign_token: 's4b',
        name: 'Carla Lima',
        email: 'carla@editoradigital.com',
        role: 'external',
        position: 2,
        signed_at: daysAgo(10),
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(14),
    sent_at: daysAgo(13),
    completed_at: daysAgo(10),
    expires_at: null,
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c4',
    signed_pdf_url: 'https://files.zapsign.com.br/c4-signed.pdf',
    linked_client_id: null,
    linked_client_name: null,
    linked_project_id: 'prj-verao26',
    linked_project_name: 'Campanha Verão 2026',
    linked_supplier_id: 'sup-carla',
    linked_supplier_name: 'Carla Lima (PJ)',
    value_brl: 12000,
    linked_at: daysAgo(13),
    notes: 'Edição da abertura + 6 cortes. Entrega final acordada com Marina.',
    imported_at: daysAgo(14),
  },

  // 5 · Project · expired (vai pra Arquivados)
  {
    id: 'c5',
    zapsign_doc_token: 'tok_c5',
    title: 'Contrato de Direção — Projeto Cancelado Q1',
    status: 'expired',
    party_type: 'client',
    contract_class: 'project',
    recurrence: null,
    signers: [
      {
        zapsign_token: 's5a',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 1,
        signed_at: null,
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(95),
    sent_at: daysAgo(94),
    completed_at: null,
    expires_at: daysAgo(60),
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c5',
    signed_pdf_url: null,
    linked_client_id: 'cli-velho',
    linked_client_name: 'Cliente Cancelado',
    linked_project_id: null,
    linked_project_name: null,
    linked_supplier_id: null,
    linked_supplier_name: null,
    value_brl: 40000,
    linked_at: daysAgo(94),
    notes: null,
    imported_at: daysAgo(95),
  },

  // 6 · Recurring · vigente, longe do fim (auto-renova)
  {
    id: 'c6',
    zapsign_doc_token: 'tok_c6',
    title: 'Retainer Mensal — Agência Construct',
    status: 'signed',
    party_type: 'client',
    contract_class: 'recurring',
    recurrence: {
      start_date: daysFromNow(-180),
      end_date: daysFromNow(185),
      auto_renew: true,
      notice_period_days: 60,
      frequency: 'annual',
      adjustment_index: 'IPCA',
      adjustment_percent: null,
      next_adjustment_at: daysFromNow(185),
      amount_brl: 45000,
    },
    signers: [
      {
        zapsign_token: 's6a',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 1,
        signed_at: daysAgo(180),
        refused_at: null,
      },
      {
        zapsign_token: 's6b',
        name: 'Pedro Construct',
        email: 'pedro@construct.com.br',
        role: 'external',
        position: 2,
        signed_at: daysAgo(178),
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(182),
    sent_at: daysAgo(181),
    completed_at: daysAgo(178),
    expires_at: null,
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c6',
    signed_pdf_url: 'https://files.zapsign.com.br/c6-signed.pdf',
    linked_client_id: 'cli-construct',
    linked_client_name: 'Agência Construct',
    linked_project_id: null,
    linked_project_name: null,
    linked_supplier_id: null,
    linked_supplier_name: null,
    value_brl: 45000,
    linked_at: daysAgo(181),
    notes: 'Janela de não-renovação: 60 dias antes do aniversário.',
    imported_at: daysAgo(182),
  },

  // 7 · Recurring · expiring_critical (≤30d) — vai pro banner vermelho
  {
    id: 'c7',
    zapsign_doc_token: 'tok_c7',
    title: 'Contrato de Manutenção — Estúdio Sul',
    status: 'signed',
    party_type: 'company',
    contract_class: 'recurring',
    recurrence: {
      start_date: daysFromNow(-355),
      end_date: daysFromNow(22),
      auto_renew: false,
      notice_period_days: 30,
      frequency: 'annual',
      adjustment_index: 'fixed_percent',
      adjustment_percent: 8,
      next_adjustment_at: daysFromNow(22),
      amount_brl: 9800,
    },
    signers: [
      {
        zapsign_token: 's7a',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 1,
        signed_at: daysAgo(355),
        refused_at: null,
      },
      {
        zapsign_token: 's7b',
        name: 'Estúdio Sul',
        email: 'contato@estudiosul.com.br',
        role: 'external',
        position: 2,
        signed_at: daysAgo(354),
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(358),
    sent_at: daysAgo(357),
    completed_at: daysAgo(354),
    expires_at: null,
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c7',
    signed_pdf_url: 'https://files.zapsign.com.br/c7-signed.pdf',
    linked_client_id: null,
    linked_client_name: null,
    linked_project_id: null,
    linked_project_name: null,
    linked_supplier_id: 'sup-estudiosul',
    linked_supplier_name: 'Estúdio Sul Locação',
    value_brl: 9800,
    linked_at: daysAgo(357),
    notes: null,
    imported_at: daysAgo(358),
  },

  // 8 · Recurring · expired (já passou da vigência sem renovar)
  {
    id: 'c8',
    zapsign_doc_token: 'tok_c8',
    title: 'Cessão de Imagem Recorrente — Talent Lucas Ribeiro',
    status: 'signed',
    party_type: 'talent',
    contract_class: 'recurring',
    recurrence: {
      start_date: daysFromNow(-720),
      end_date: daysFromNow(-15),
      auto_renew: false,
      notice_period_days: 30,
      frequency: 'annual',
      adjustment_index: 'none',
      adjustment_percent: null,
      next_adjustment_at: null,
      amount_brl: null,
    },
    signers: [
      {
        zapsign_token: 's8a',
        name: 'Gabriel Hiro',
        email: 'gabriel@hiro.film',
        role: 'internal',
        position: 1,
        signed_at: daysAgo(720),
        refused_at: null,
      },
      {
        zapsign_token: 's8b',
        name: 'Lucas Ribeiro',
        email: 'lucas@talents.com',
        role: 'external',
        position: 2,
        signed_at: daysAgo(719),
        refused_at: null,
      },
    ],
    zapsign_description: null,
    created_at: daysAgo(722),
    sent_at: daysAgo(721),
    completed_at: daysAgo(719),
    expires_at: null,
    zapsign_doc_url: 'https://app.zapsign.com.br/docs/c8',
    signed_pdf_url: 'https://files.zapsign.com.br/c8-signed.pdf',
    linked_client_id: null,
    linked_client_name: null,
    linked_project_id: null,
    linked_project_name: null,
    linked_supplier_id: null,
    linked_supplier_name: null,
    value_brl: null,
    linked_at: daysAgo(721),
    notes: null,
    imported_at: daysAgo(722),
  },
];
