// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oddxoicvreymmeynfxxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZHhvaWN2cmV5bW1leW5meHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjg0NjIsImV4cCI6MjA2OTMwNDQ2Mn0.IffCg2BlXqEQWI11AmHryk9O4_KngfoWquEkWn5hg_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});